site_name: "Hunt Down The Freeman: Technical Documentation"
theme:
  name: material
  palette:
    scheme: slate
  highlightjs: true
  hljs_languages:
     - yaml
     - rust
     - c++
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
