site_name: "Hunt Down The Freeman: Technical Documentation"
theme:
  name: material
  highlightjs: true
  hljs_languages:
      - yaml
      - rust
      - c++


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
